services:
  postgres:
    image: postgres:17-alpine
    container_name: miniurl-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: miniurl
      POSTGRES_PASSWORD: miniurl123
      POSTGRES_DB: miniurl_db

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  memcached:
    image: memcached:1.6-alpine
    container_name: miniurl-memcached
    restart: unless-stopped

    ports:
      - "11211:11211"

    command: memcached -m 64

  um_service:
    build:
      context: ./services/um_service
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./services/um_service/.env
    ports:
    - "6001:6001"

volumes:
  postgres-data: